<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);Engine/obj/**;Engine/bin/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine.Core\Engine.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
